<?php
require_once ('articles.theme.inc'); 
function articles_menu() {
    $items = array();
     $items['articles'] = array(
        'title'             =>  'Articles View',  //page title
        'description'       =>  'Articles Information',  //description show when mouse hover on link
        'page callback'     =>  'articles_list',  //callback function which is invoked when menu item is called.
        'access callback'   =>  true,  //any user can access this page
       );
     return $items;
}

function articles_list() {
    // select all rows from books table
    
    //$query = db_select('movies1', 'tr')->fields('tr');



// execute above query to get the results from database table.
//$result = $query->execute();

//send data to custom theme template
//theme books_list created under sites\all\themes\custom\fiction\templates\books\books-list.tpl.php

//$output = theme('articles_list', array('data'=> $result)); 
$output = theme('articles_list', array('data'=> array('books_title'=>'algorithm1'))); 
return $output;
}